# Generated by Django 3.1.1 on 2020-09-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_changedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, upload_to='origin/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
